# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd99f0f281a08bb9f382e3d54a755e94137a1a1dcd4af8c1ea15cb76f1d5adc300cee7b38c830ab62ffd6f961d70f419b6433b646da99a877021bcd6ab2b5264

test:
  secret_key_base: 5856ed30f4d03c56228837357c164341b5a7b46d05668c66a7b49fdeb1757c9c9a3bbf92c5612e72acebc2e6da07112906625dcb3b786a7431875d175b6460d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
